name: My First Pipeline

# Trigger: When to run?
on: [push]

# Jobs: What to do?
jobs:
  say-hello:
    runs-on: ubuntu-latest  # This is a VM provided by GitHub for free!
    steps:
      - name: Print a greeting
        run: echo "Hello! I am a robot running on GitHub's servers."

      - name: Check OS
        run: cat /etc/os-release

      - name: version python
        run: python3 --version
